spring.application.name=gateway
server.port=8080

spring.cloud.gateway.routes[0].id=service-a-route
spring.cloud.gateway.routes[0].uri=lb://service-a
spring.cloud.gateway.routes[0].predicates[0]=Path=/a/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=service-b-route
spring.cloud.gateway.routes[1].uri=lb://service-b
spring.cloud.gateway.routes[1].predicates[0]=Path=/b/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[2].id=service-c-route
spring.cloud.gateway.routes[2].uri=lb://service-c
spring.cloud.gateway.routes[2].predicates[0]=Path=/c/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
